### ISSUE TITLE
Add a on_completion_command option

### ISSUE THREAD

**Issue by scorsi** [simplesurance/baur#156]
Hello,

It could be nice to specify a command to execute once the `Build.Output` task has finished.

To explain a little bit why I need something like this, here my project/workflow example :

I have a mono-repo with all my different services of my application, all services dispose of a IaC in Terraform, to deploy new versions I need to notify Terraform Cloud to start the infrastructure migration (to deploy the new zip file or to make changes on the infrastructure). I have a CI/CD which manage all of this for me, from the building to the deploying.
So here the workflow: baur build -> gradle build -> baur output s3 file -> terraform plan/apply.

Maybe I can do that without a new task option ? Actually, I'm rebuilding all my services/infrastructures on any changes. Do you have any idea ?

Thanks,

**Comment by scorsi** [comment]
Maybe with something like:
```toml
name = "enrichment-service"
[Build]
  command = "gradle build"
  on_completion_command = "terraform apply -var=$DIST_FILE"
  includes = ["$ROOT/baur/gradle-service.toml"]
  [Build.Input]
    [Build.Input.GitFiles]
      paths = ["src/**/*", "resources/**/*"]
  [Build.Output]
    [[Build.Output.File]]
      path = "build/destinations/$APPNAME.zip"
      [Build.Output.File.S3Upload]
        dest_file = "/$APPNAME-$GITCOMMIT.zip"
```
The file is uploaded as `/$APPNAME-$GITCOMMIT.zip` to S3 and then if successfully pushed, `on_completion_command` is ran with `$DIST_FILE` parameter.

**Comment by scorsi** [comment]
Ok it's resolved with #78 and #155 ?

**Comment by fho** [comment]
Multiple ideas come to my mind:


1. In our CI setup build and deployment are separate jobs. After the `baur build` job, the deploy job might be triggered. 
The deploy job records the application, it's version, a checksum of the deploy files and the deploy-target
When the deploy job is executed, it get the list of application in the repository via `baur ls apps -f name,git-commit`. Then it checks for each application if the last deployed version of the app is the same and if the deploy file checksum match if not it runs the deploy job.

2. Structure the CI job like (pseudo code):  
 ```
for app, status = $(baur ls apps --csv -f name,build-status) {
  if status != "pending {
     continue
  }

  baur build $app
  DIST_FILE=$(baur ls apps --csv -f path $app)/destinations/$app.zip)
  terraform apply -var 'artifact_file=$DIST_FILE' -auto-approve
}
 ```  
 Resolving and hashing the build inputs for the pending applications twice is an overhead but should not matter much.

3. `baur build` could print (or write to a file) a report in csv format that lists the build application at the end, easier to process then parsing the current `baur build` output and more resilient

4. I still would like to prevent introducing dependencies but it would also be good usecase for it. :-)
When baur supports to define multiple task per app, a post task could be defined that is run after build via a dependency. 

Having a `on_completion_command` is also a good idea

**Comment by fho** [comment]
> Ok it's resolved with #78 and #155 ?

No, it does not solve it.
The execution of the task is not ordered.

**Comment by scorsi** [comment]
Ok, it's approximatively what I was thinking to do.
Thanks for your time ! You can close this issue if you don't plan to add `on_completion_command` or something which could help doing that with the new task system (like a `depends_on` option).
